### ISSUE TITLE
Merge in League Gothic Extended

### ISSUE THREAD

**Issue by micahbrich** [theleagueof/league-gothic#1]
Dancci added to League Gothic with a Latin Extended-A character set. We should merge that in!

![Poster image](http://media.tumblr.com/tumblr_l6bxyz4LYu1qaidj6.jpg)
http://typethefont.com/post/798257771/league-ghotic-extended

**Comment by alerque** [comment]
What @grzegorzrolek said. Nope nope and nope.

Note a variable font overhaul is in the works with actual *design* involved.
