### ISSUE TITLE
New webfont set looks strange for smaller font sizes

### ISSUE THREAD

**Issue by ghost** [theleagueof/league-gothic#10]
Here is a gif showing the difference, note the font at the bottom where the red arrow is. The characters have different height. R D P S remains big, rest go small.

http://i.imgur.com/NB0z7.gif

The first frame shows the old download (which looks nice), the second the updated set. Both are League Gothic Regular.

**Comment by alerque** [comment]
The image you posted is no longer available, but this sounds like a hinting issue. This is an unhinted font and not a great choice for super small sizes unless you have control over the rasterization process. The size inconsistency you are seeing is an artifact of the hinter in your operating system, not this font. An upcoming Variable font overhaul will likely make this less noticable with automatic hinting, but this will not be changed in the current generation of releases.
