### ISSUE TITLE
.woff rendering some characters wrong

### ISSUE THREAD

**Issue by bhardy** [theleagueof/league-gothic#11]
In Chrome some of the characters are showing up wrong for league-gothic. It looks perfect in Firefox and IE, but something is wrong with Chrome. When I inspect the element, and go to the Resources tab and click on the font, you can see the errors in there. It looks correct up to 'font-size: 48px' but at anythign higher than that you can see problems with: X, k, w, and x.

I have tested this on 2 different projects and 2 different computers and I have removed everything from the index that could be somehow interferring with it.

I feel like it must somehow be on my end since no one else has reported this issue... but I'm pretty sure it isn't!

![font-error](https://f.cloud.github.com/assets/1272130/615269/22178b5a-ce33-11e2-9bbb-dead28b889da.jpg)

**Comment by alerque** [comment]
I don't have access to any version of iOS to check this, but I'd be very surprised to learn if this was still an issue in anything current (either iOS or the current release of the font). The 1.600 release was built with different tooling which almost certainly makes this a non-issue. If anybody does still have a problem please feel free to comment or open a new issue.
