### ISSUE TITLE
Switch to UFO only

### ISSUE THREAD

**Issue by grzegorzrolek** [theleagueof/league-gothic#2]
Folks, I think it's unnecessary and in fact quite confusing to have a FL binary alongside UFO sources. Frankly, I myself wouldn't want to even touch the binary. How are you going to keep it sync? The font's structure and features is not complicated so to need such a binary. Yeah, I've seen there's a background layer with outlines of some design decisions or so, but this could be easily exported as accordingly titled supplement, which could be merged back into the main UFO package with the upcoming layer support. I really would like to put my hands onto the sources now, but I'm worried that my work will somehow be overwritten by some future FL exports.

**Comment by alerque** [comment]
Done. The canonical source format is actually currently Glyphs, not UFO, but I have removed the duplicate sources. You can work on the font in a UFO editor using Fontship to handle round-trips to Glyphs.
