### ISSUE TITLE
add a package.json

### ISSUE THREAD

**Issue by arianra** [theleagueof/league-gothic#21]
Please consider adding a package.json to the repo, see: https://docs.npmjs.com/files/package.json

It lets npm identify this repository as a package, allowing us to use npm to manage it as a dependency for our projects.

**Comment by seanwalsh** [comment]
:thumbsup:

**Comment by sachindra149** [comment]
:thumbsup:

**Comment by alerque** [comment]
Please follow [Fontship issue №88](https://github.com/theleagueof/fontship/issues/88) and [fontsource issue №66](https://github.com/fontsource/fontsource/issues/66) for progress/options on this. All the League fonts will be enabled with whatever solution is arrived at between those two.
