### ISSUE TITLE
Quotation marks are different?

### ISSUE THREAD

**Issue by primalbet** [theleagueof/league-gothic#24]
http://image.prntscr.com/image/3c6c5952d77a44c9bc7f7021549e287d.png

Check the screenshot. When I use this font, my quotation marks are # 1 on that pic. However i've seen other people use the same font but their quotation marks are # 2 on the pic. How? I want my quotation marks to be # 2.

**Comment by 153957** [comment]
You are using 'smart quotes', which are curly quotes, which can be useful to indicate the start and end of a quotation.
Typewriter quote: ' (<- You can copy/paste this character to use where you want the straight quote)
Curly quote: ’

https://en.wikipedia.org/wiki/Quotation_marks_in_English#Smart_quotes

Some operating systems automatically try to use smart quotes, this can often be disabled.
On OS X (macOS): System Preferences -> Keyboard -> Text -> 'Use smart quotes and dashes'
