### ISSUE TITLE
Google Fonts Family Name issue

### ISSUE THREAD

**Issue by davelab6** [theleagueof/league-gothic#29]
Last year @bghryct worked on polishing this up a bit further so Google Fonts can onboard it (https://github.com/bghryct/league-gothic) and one nuanced issue @m4rc1e raised is that the family doesn't have a range of weights. 

Therefore the "regular" styles are marked as `400` weights in the `OS/2` table (and the VF `wght` axis) 

This creates a potential problem in the future where lighter weights are added. If this is expected, then the Google Fonts policy is to append ` One` to the family name (https://fonts.google.com/?query=One - particularly https://fonts.google.com/specimen/Fjalla+One which is in the same genre) 

However, since this family has over 1M download from LOMT, I'd like to avoid that and keep the name 'as is'

But therefore, if in the future this family is expanded with more Weights, it would be good to re-release that with a (slightly?) different family name, such as "League Sans" :)

Does that sound good?

**Comment by bghryct** [comment]
Sounds good. Happy to help with that expansion when it becomes desirable/necessary.

**Comment by alerque** [comment]
Do I understand correctly here that the concern is that the current font design is not anything close to a 400 weight, but it's seen so much deployment that fixing the current font style by assigning it a 600 weight and calling it Bold (or whatever is appropriate), even with a new font version number, would throw a lot of people off their game?

**Comment by bghryct** [comment]
I think that's exactly it.

**Comment by davelab6** [comment]
I'll proceed
