### ISSUE TITLE
validation problems — 'name' table structure

### ISSUE THREAD

**Issue by adiabatic** [theleagueof/league-gothic#3]
When I opted to install League Gothic.otf (4f9ff8d) on my computer running Lion, Font Book said that a problem may have been found with it. In particular, I have a yellow exclamation point where it says "'name' table structure".

Is this something I need to be concerned about?

**Comment by alerque** [comment]
I think this is fixed in [1.600](https://github.com/theleagueof/league-gothic/releases/tag/1.600). There were actually several meta data issues involving how the font styles were linked together.
