### ISSUE TITLE
Font display error

### ISSUE THREAD

**Issue by BG7YWL** [theleagueof/league-gothic#31]
"files" cannot display "i" properly

![Snipaste_2020-07-17_16-33-06](https://user-images.githubusercontent.com/9145406/87766121-43928680-c84b-11ea-9d30-f9bb3aa68dfd.png)

**Comment by alerque** [comment]
[The `fi` pair is drown as a ligature](https://en.wikipedia.org/wiki/Orthographic_ligature). If you don't want the ligature and want the separate glyphs instead you need to disable that feature in your software. I don't recognize what program you are using there and can't tell you where to find the feature, but disabling ligatures is what you are looking for. If your software doesn't support enabling or disabling font features you can either hack it by adding zero width joiners between pairs you don't want to display as ligatures or use a utility to build a copy of the font files with the features you want enabled or disabled by default.

**Comment by BG7YWL** [comment]
solved
![Snipaste_2020-07-17_23-37-41](https://user-images.githubusercontent.com/9145406/87804481-845bc100-c886-11ea-80c2-bbf7ccc6753d.png)

**Comment by alerque** [comment]
Glad you found it. Is that Corel Draw? I heard the latest release had better support for font features.

**Comment by BG7YWL** [comment]
Yes, it is Corel Draw. I am using the X8 version
