### ISSUE TITLE
Adding example stylesheet for the webfonts would be convenient

### ISSUE THREAD

**Issue by davecranwell** [theleagueof/league-gothic#4]
e.g

```
@font-face {
    font-family: 'LeagueGothic';
    src: url('League_Gothic-webfont.eot');
    src: url('League_Gothic-webfont.eot?#iefix') format('embedded-opentype'),
             url('League_Gothic-webfont.woff') format('woff'),
             url('League_Gothic-webfont.ttf') format('truetype'),
             url('League_Gothic-webfont.svg#LeagueGothic') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

**Comment by alerque** [comment]
The current releases don't have any CSS sheets included, but just the WOFF2 format is pretty simple to setup these days. See [this issue](https://github.com/theleagueof/fontship/issues/77) if you have ideas for what CSS should be included, and also note [this issue](https://github.com/fontsource/fontsource/issues/66) for possible integration with fontsource which makes webfont embedding easier. Follow those issues for changes in this department.
