### ISSUE TITLE
Documents using old League Gothic says the font is missing

### ISSUE THREAD

**Issue by nadangergeo** [theleagueof/league-gothic#9]
Old documents and design files which use League Gothic complain that the font is missing, since I deleted it before installing the new version with italic and condensed. 

I'm not sure having both the new and old font installed is the optimal solution, since they appear under the same family under the same name (Regular) and thus easily mixed up. Updating every single file that uses the old font is not a solution either.

Perhaps updating the name to League Gothic 2.0 is a solution, what do you guys think?

**Comment by alerque** [comment]
This appears to relate to early releases that didn't have "League Gothic" as the normalized family name. This hasn't been the case for ages, and many more font name related issues were addressed in 1.600. Note there is an upcoming variable font release which will change the instance situation *again*. No we're not going to rename font family names on every release, that is a problem that needs to be addressed in other tooling.
